<p>Страница <?php echo $this->current; ?> из <?php echo $this->pageCount;?></p>

<?php if ($this->current != $this->first): ?>
    <a href="<?php echo $this->url(array('page' => $this->first)); ?>">Первая</a>
<?php else: ?>
    Первая
<?php endif; ?>

<?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">Предыдущая</a>
<?php else: ?>
    Предыдущая
<?php endif; ?>

<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
    <?php else: ?>
        <?php echo $page; ?>
    <?php endif; ?>
<?php endforeach; ?>

<?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(array('page' => $this->next)); ?>">Следующая</a>
<?php else: ?>
    Следующая
<?php endif; ?>

<?php if ($this->current != $this->last): ?>
    <a href="<?php echo $this->url(array('page' => $this->last)); ?>">Последняя</a>
<?php else: ?>
    Последняя
<?php endif; ?>
